version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/account_db"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "1111"
    ports:
      - "8080:8080"

  db:
    image: postgres:14.5
    environment:
      POSTGRES_DB: "account_db"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1111"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db:/docker-entrypoint-initdb.d
#    entrypoint: ["/docker-entrypoint-initdb.d/init-db.sh"]
#  database:
#    image: postgres:14.5
#    ports:
#      - "5432:5432"
#    environment:
#      POSTGRES_USER: "postgres"
#      POSTGRES_PASSWORD: "postgres"
#      POSTGRES_DB: "ostock_dev"
#    volumes:
#      - postgres:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
#      - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql

volumes:
  postgres_data:
  postgres:
