version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/account_db
      SPRING_DATASOURCE_USERNAME: account_db
      SPRING_DATASOURCE_PASSWORD: 1111
    ports:
      - "8080:8080"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: account_db
      POSTGRES_USER: account_db
      POSTGRES_PASSWORD: 1111
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: