create table users
(
    id       integer generated by default as identity
        constraint user_pkey
            primary key,
    username varchar(100) not null,
    password varchar(100) not null,
    role     varchar(20) CHECK (role = 'ROLE_USER' or role = 'ROLE_ADMIN')
);

create table accounts
(
    acc_number integer generated by default as identity
        constraint acc_number
            primary key,
    acc_value  integer,
    status     varchar(20) check (status = 'BLOCKED' or status = 'ACTIVE'),
    user_id    integer
        constraint fk_accounts_users
            references users
);

INSERT INTO users(username, password, role)
VALUES ('Anna09', 'Anna09', 'ROLE_ADMIN'),
       ('Mike2010', 'Mike2010', 'ROLE_USER'),
       ('Apricot', 'Apricot', 'ROLE_USER'),
       ('Kate', '536325', 'ROLE_USER');

INSERT INTO accounts(acc_value, status, user_id)
VALUES (2300, 'ACTIVE', 2),
       (900, 'ACTIVE', 3),
       (1000, 'ACTIVE', 4),
       (870, 'BLOCKED', 2);

